### ISSUE TITLE
Unable to run the demo using VS 2015 CTP 6

### ISSUE THREAD

**Issue by prasannapattam** [Microsoft/ngconf2015demo#23] opened 2015-04-19 10:32 UTC
I was able to get the demo running using Node. I wanted to make changes to todo.ts using VS. But it seems that TypeScript 1.5 is not registered properly. To register TypeScript, I did the following
powershell -ExecutionPolicy Bypass
 vs\VSDevMode.ps1 -vsVersion 14 -tsScript tsc\

Here is the regedit screenshot
![reged](https://cloud.githubusercontent.com/assets/4832935/7219080/b2c73b8a-e6ac-11e4-998b-5a75bd6396bd.png)

As mentioned in the issue #19 I copied the "lib.d.ts, lib.es6.d.ts, typescriptServices.js" from demo/tsc on to "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript". 
But still my changes to the todo,ts are not getting compiled by Visual Studio

Am I missing something?

**Comment by mhegazy** [comment] 2015-04-20 17:08
Just to make sure i understand the issue correctly, you can see the correct behavior while editing in Visual Studio, the issue is building from VS (i.e F5). is this accurate?

if so, this is not supported at the moment. The only supported build is using node on the command line.

If you still want to build using VS, you will need to patch your tsc.exe, i can  point you to how to patch your system to get this done.

**Comment by prasannapattam** [comment] 2015-04-21 00:36
Yes. I would like VS to generate the js files when I save ts file or do build (F5). As you mentioned, I need to patch tsc.exe

Also looks like the demo is using earlier version of Angular. As you know "!foreach" is changed to "*foreach". How can I update the Angular version to the latest release (alpha15). Where would I get ".d.ts" files? I could not see this on Definitely Typed GitHub site.

**Comment by mhegazy** [comment] 2015-04-21 04:43
Please note that this is demo is a snapshot of Angular 2.0 and TypeScript 1.5; both teams are working hard on getting the full support in both code bases currentelly. so if you can bear with us for a little bit, we should have everything working on latest out-of-the-box.

The changes you made will make your compile-on-save in VS work.
for build, you will need to patch your tsc.js and lib.d.ts in C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4
1. make a backup copy of your 1.4 folder contents
2. copy tsc\tsc.js from your demo folder to C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4\tsc.js
3. copy tsc\lib.d.ts to C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4\lib.d.ts

build should now give you the same results as:
node tsc\tsc.js

**Comment by prasannapattam** [comment] 2015-04-21 16:00
Thanks for instructions on patching tsc.
I wanted to try out Angular 2.0 using TypeScript. As per your comment I may not currently be able to use latest Angular with latest typescript. I guess I will try Angular 2.0 using Javascript.

**Comment by mhegazy** [comment] 2015-04-24 23:57
@prasannapattam, with help from the @angular2 team we got the demo updated (https://github.com/Microsoft/ngconf2015demo/commit/18d6be67e86bb1f60924005209e140d80ec11bc6). give it a try, and let us know how it goes. sorry for the delay.

**Comment by prasannapattam** [comment] 2015-04-25 14:49
Great. I was able to run the demo with your version.

What version of Angular are you using. I observed some customization of Angular2 to make this runnable. Will these changes be part of Angular or part of TypeScript. 

I used the following Angular2 version to compare
https://code.angularjs.org/2.0.0-alpha.20/

**Comment by mhegazy** [comment] 2015-04-25 15:10
This is a bundle created by the angular team to make it easy to use in this demo. By next week we should remove the checked in bundel and use the live one from https://code.angularjs.org/2.0.0-alpha.20/ so stay tuned :)

**Closed as completed** 2016-01-02 03:04 UTC
